kind: pipeline
name: Mystic Kernel (MSM-4.4)

branches:
  only:
    - circleci-project-setup

steps:
- name: Building Mystic Kernel
  image: okta10/docker:debian
  environment: 
    TOKED:
      from_secret: TOKED
    TELEGRAM_TOKEN:
      from_secret: TELEGRAM_TOKEN
    CHANNEL_ID:
      from_secret: CHANNEL_ID

  commands:
    - "wget https://raw.githubusercontent.com/okta-10/scripts/main/build-ci/kernel-4.4/doStart"
    - bash doStart beta
    - cd kernel
    - "wget https://raw.githubusercontent.com/okta-10/scripts/main/build-ci/kernel-4.4/doPush"
    - bash build whyred
    - bash build a26x
    - bash build lavender
    - "wget https://raw.githubusercontent.com/okta-10/scripts/main/patch/oc_4.4.patch"
    - git apply oc_4.4.patch
    - bash build whyred oc
    - bash doPush beta
